### ISSUE TITLE
Got this tensorflow error.

### ISSUE THREAD

**Issue by victorvondoom25** [Dragjon/Chess-Ai-Training#3]
![image](https://github.com/user-attachments/assets/953fab7d-be58-47d0-b2a2-2e20bbdea1ba)

Can you update this project.

**Comment by victorvondoom25** [comment]
> ![image](https://private-user-images.githubusercontent.com/86470814/359436005-953fab7d-be58-47d0-b2a2-2e20bbdea1ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDkzMDQsIm5iZiI6MTcyNDE0OTAwNCwicGF0aCI6Ii84NjQ3MDgxNC8zNTk0MzYwMDUtOTUzZmFiN2QtYmU1OC00N2QwLWIyYTItMmUyMGJiZGVhMWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEwMTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMTY5ZjIxZWQxNDAzNTlkZTQ4ODQ1ZTZlY2IyMGJmZDMzNjUzNDhmMDM5OTk1MDUwZDNkZDZhMzJkMjgzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ameb1wREY-fBeIU05fgzsrCZ-9-2IB17lEd9zzm8LA0)
> 
> Can you update this project.

I think the estimator is now depricated.

**Comment by Dragjon** [comment]
Oh wow, I haven't worked on this for quite a while. Will update it as soon as possible.

**Comment by victorvondoom25** [comment]
> Oh wow, I haven't worked on this for quite a while. Will update it as soon as possible.

Thanks!

**Comment by Dragjon** [comment]
Yep the estimator is deprecated from tensorflow 2.16.1 onwards. You can temporarily uninstall and install the older version
```
pip uninstall tensorflow
pip install tensorflow==2.15.1
```
From [This](https://www.tensorflow.org/guide/estimator)

**Comment by victorvondoom25** [comment]
> Yep the estimator is deprecated from tensorflow 2.16.1 onwards. You can temporarily uninstall and install the older version
> 
> ```
> pip uninstall tensorflow
> pip install tensorflow==2.15.1
> ```
> 
> From [This](https://www.tensorflow.org/guide/estimator)

Is there any way it can be used on lichess as a UCI engine?

**Comment by Dragjon** [comment]
You have to write your own uci parsing protocol, here is a simple example in python
```python
def parse_parameters(line):
    DEFAULT_WTIME = float('inf')
    DEFAULT_BTIME = float('inf')
    parameters = line.split()[1:]
    wtime, btime = DEFAULT_WTIME, DEFAULT_BTIME

    for i in range(len(parameters)):
        if parameters[i] == "infinite":
            wtime = float('inf')
            btime = float('inf')
        elif parameters[i] == "wtime" and i + 1 < len(parameters):
            wtime = float(parameters[i + 1])
        elif parameters[i] == "btime" and i + 1 < len(parameters):
            btime = float(parameters[i + 1])
    return wtime, btime


def play_chess():
    global board, start_time
    remaining_time = 1000000

    while True:
        line = input()
        if line == "uci":
            print("id name My Engine Name")
            print("id author My Name")
            print("uciok")
        elif line == "isready":
            print("readyok")
        elif line.startswith("position startpos"):
            board = chess.Board()
            if "moves" in line:
                _, moves_part = line.split("moves")
                moves = moves_part.strip().split()
                for move in moves:
                    board.push_uci(move)
        elif line.startswith("position fen"):
            _, fen = line.split("fen ")
            fen = fen.split(" ")
            fen = fen[0] + " " + fen[1] + " " + fen[2] + " " + fen[3] + " " + fen[4] + " " + fen[5]
            board.set_fen(fen)
            if "moves" in line:
                _, moves_part = line.split("moves")
                moves = moves_part.strip().split()
                for move in moves:
                    board.push_uci(move)
        elif line.startswith("go"):
            wtime, btime = parse_parameters(line)
            remaining_time = wtime if board.turn == chess.WHITE else btime
            start_time = time.time()
            sb_max_time = remaining_time / sbtm
            hb_max_time = remaining_time / hbtm
            getbestmove()
        elif line == "quit":
            break
```
* Then you have to build it into an executable, and you can use [lichess-bot](https://github.com/lichess-bot-devs/lichess-bot)
* You can refer to the UCI protocol [here](https://gist.github.com/DOBRO/2592c6dad754ba67e6dcaec8c90165bf)
